# Generated by Django 5.1.4 on 2025-08-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('block_number', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
