# Generated by Django 5.1.4 on 2025-08-06 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainlog',
            name='actor',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('pharmacy', 'Pharmacy'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='blockchainlog',
            name='log_type',
            field=models.CharField(choices=[('creation', 'Batch Creation'), ('transfer', 'Drug Transfer'), ('verification', 'Verification'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockchainlog',
            name='block_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='blockchainlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
