# Generated by Django 5.1.4 on 2025-06-16 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0006_batch_quantity_left'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.PositiveIntegerField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.batch')),
                ('distributor', models.ForeignKey(limit_choices_to={'role': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(limit_choices_to={'role': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_distributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
