# Generated by Django 5.1.4 on 2025-07-11 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_pharmacydistribution_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacydistribution',
            name='pharmacy',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_distributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
