# Generated by Django 5.1.4 on 2025-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='qr_code_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
