# Generated by Django 5.1.4 on 2025-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='batch_codes/'),
        ),
    ]
