# Generated by Django 5.1.4 on 2025-06-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_drug_qr_code_string_drug_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='qr_code_string',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
