# Generated by Django 5.1.4 on 2025-06-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_alter_drug_qr_code_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='drug_category',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
