# Generated by Django 5.1.4 on 2025-08-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_drug_scanned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
