# Generated by Django 5.1.4 on 2025-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_batch_drug_category_batch_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
