# Generated by Django 5.1.4 on 2025-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_batch_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdistribution',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
