# Generated by Django 5.1.4 on 2025-06-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0006_batch_quantity_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='verified',
        ),
        migrations.AddField(
            model_name='batchdistribution',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
